[workspace]
resolver = "3"
members = ["lapdog", "lapdog-derive"]
default-members = ["lapdog"]

[workspace.package]
license = "MIT"
repository = "https://github.com/HEGGEMANN-AG/lapdog"
authors = ["Niclas Klugmann <klugmann@heggemann.com>"]
