[package]
name = "lapdog"
authors.workspace = true
license.workspace = true
repository.workspace = true
version = "0.1.0"
edition = "2024"
description = "A safer sync LDAP library"
documentation = "https://docs.rs/lapdog"

[dependencies]
rasn = "0.27.0"
rasn-ldap = "0.27.0"
lapdog-derive = { version = "0.1.0", optional = true, path = "../lapdog-derive" }

[features]
default = ["derive"]
derive = ["dep:lapdog-derive", "from_octets"]
from_octets = []